#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import inquirer from 'inquirer';
import pc from 'picocolors';
import { Command } from 'commander';
import boxen from 'boxen';

const program = new Command();

program
  .name('env-honeypot')
  .description('Generate a massive, convincing fake .env file to trap bot scrapers.')
  .version('1.0.0')
  .parse(process.argv);

console.log(
  boxen(
    pc.yellow(pc.bold('🍯 ENV HONEYPOT')) + '\n' + pc.gray('Let the bots choke on fake credentials.'),
    { padding: 1, margin: 1, borderStyle: 'double', borderColor: 'yellow' }
  )
);

const cwd = process.cwd();
const targetPath = path.join(cwd, '.env.honeypot');

const generateRandomHex = (length) => {
  let result = '';
  const characters = 'abcdef0123456789';
  for (let i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return result;
};

const generateRandomString = (length) => {
  let result = '';
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  for (let i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return result;
};

const fakeKeys = [
  `# AUTOGENERATED PRODUCTION CREDENTIALS - DO NOT SHARE\n`,
  `AWS_ACCESS_KEY_ID=AKIA${generateRandomString(16).toUpperCase()}`,
  `AWS_SECRET_ACCESS_KEY=${generateRandomString(40)}`,
  `AWS_REGION=us-east-1`,
  `AWS_S3_BUCKET=prod-user-uploads-secure-${generateRandomHex(8)}\n`,
  
  `STRIPE_SECRET_KEY=sk_live_${generateRandomString(24)}`,
  `STRIPE_WEBHOOK_SECRET=whsec_${generateRandomString(24)}\n`,
  
  `DATABASE_URL=postgresql://admin:${generateRandomString(12)}@production-db-${generateRandomHex(6)}.cluster-cxxyz.us-east-1.rds.amazonaws.com:5432/main_db`,
  `REDIS_URL=redis://default:${generateRandomString(20)}@redis-prod-${generateRandomHex(6)}.upstash.io:32412\n`,
  
  `OPENAI_API_KEY=sk-${generateRandomString(48)}`,
  `ANTHROPIC_API_KEY=sk-ant-api03-${generateRandomString(64)}`,
  `HUGGINGFACE_TOKEN=hf_${generateRandomString(34)}\n`,
  
  `SLACK_BOT_TOKEN=xoxb-${Math.floor(Math.random() * 9000000000) + 1000000000}-${Math.floor(Math.random() * 9000000000) + 1000000000}-${generateRandomString(24)}`,
  `DISCORD_BOT_TOKEN=${generateRandomString(24)}.${generateRandomString(6)}.${generateRandomString(27)}\n`,

  `PAYPAL_CLIENT_ID=Ae${generateRandomString(20)}`,
  `PAYPAL_SECRET=EL${generateRandomString(20)}\n`,

  `TWILIO_ACCOUNT_SID=AC${generateRandomHex(32)}`,
  `TWILIO_AUTH_TOKEN=${generateRandomHex(32)}`,
  `SENDGRID_API_KEY=SG.${generateRandomString(22)}.${generateRandomString(43)}\n`,
  
  `GITHUB_PERSONAL_ACCESS_TOKEN=ghp_${generateRandomString(36)}`,
  `GITLAB_PRIVATE_TOKEN=glpat-${generateRandomString(20)}\n`,
  
  `# LEGACY KEYS - Slated for rotation next quarter`,
  `MONGO_URI=mongodb+srv://root:${generateRandomString(14)}@cluster0.abcde.mongodb.net/legacy_users?retryWrites=true&w=majority`,
  `GCP_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\\n${generateRandomString(64)}\\n${generateRandomString(64)}\\n${generateRandomString(64)}\\n${generateRandomString(64)}\\n-----END PRIVATE KEY-----\\n"`,
  `GCP_CLIENT_EMAIL=admin@production-project-${Math.floor(Math.random() * 900000) + 100000}.iam.gserviceaccount.com`
].join('\n');

const run = async () => {
  const { confirm } = await inquirer.prompt([{
    type: 'confirm',
    name: 'confirm',
    message: pc.yellow('Generate a fake .env.honeypot file in this directory?'),
    default: true
  }]);

  if (!confirm) {
    console.log(pc.gray('\nAborted. No honeypot deployed.'));
    process.exit(0);
  }

  if (fs.existsSync(targetPath)) {
    console.log(pc.red(`❌ .env.honeypot already exists here.`));
    process.exit(1);
  }

  fs.writeFileSync(targetPath, fakeKeys, 'utf8');

  console.log(pc.green(`\n✔ Deployed massive fake payload to .env.honeypot`));
  console.log(pc.white(`Tip: Rename it to .env and push to a public GitHub repo to waste a hacker's afternoon.`));

  console.log(pc.cyan('\nArchitected by @lakshanmuruganandam\n'));
};

run().catch(err => {
  console.error(pc.red('\nAn unexpected error occurred:'), err.message);
  process.exit(1);
});
